language: python
python:
  - 3.8
dist: trusty
env:
  global:
    - APP_SETTINGS="test"
    - FLASK_APP="app:create_app('${APP_SETTINGS}')"
    - FLASK_ENV="testing"
install:
  - pip install -r requirements.txt
  - python manage.py db upgrade
script:
  - coverage erase
  - coverage run manage.py test
  - coverage report -m 
